# Generated by Django 3.2.9 on 2022-02-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen1')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen2')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen3')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
